phpcfdi/cfdi-sat-scraper

src/DownloadXML.php
src/Metadata.php
src/MetadataExtractor.php
src/MetadataList.php
src/QueryResolver.php
tests/FakesFactory/Fakes.php
tests/Unit/MetadataExtractorTest.php
tests/Unit/MetadataListTest.php
tests/Unit/MetadataTest.php
tests/_files/fake-to-extract-metadata-missing-uuid.html

- Add Metadata (immutable) object to store extracted tuples, this is a major improvement in memory and avoid to copy arrays all around
- Refactor MetadataExtractor, MetadataList, DownloadXML & QueryResolver to work with previous structure
- Increase code coverage
See full list of commits to review refactor

Introduce Metadata as an item of MetadataList

---

src/Filters/FiltersReceived.php

Al filtrar los cfdis recibidos de los meses 01 a 09 (Enero - Septiembre), siempre se retornaban los cfdis del mes 1 (Enero).

fix filter

---

src/Internal/ParserFormatSAT.php
src/ParserFormatSAT.php
src/QueryResolver.php
tests/Unit/Internal/ParserFormatSatTest.php
tests/Unit/ParserFormatSatTest.php

The commits have a complete history of this change
summary: no need a constructor, things to parse are given as a parameter, understand format, simplify logic, add phpdoc, etc.
This class has been included on Internal namespace

Test and refactor ParserFormatSat

---

.travis.yml
composer.json
phpstan.neon.dist
src/Captcha/Resolvers/DeCaptcherCaptchaResolver.php
src/Contracts/Filters.php
src/DownloadXML.php
src/Filters/BaseFilters.php
src/Filters/FiltersIssued.php
src/Filters/FiltersReceived.php
src/HtmlForm.php
src/Query.php
src/SATScraper.php
tests/Unit/MetadataListTest.php
tests/Unit/SatScraperPropertiesTest.php

- Query::uuid property is never null
- BaseFilters must detect if the query is about uuid or dates, filters are different on each case
- It was returning an array instead of a filter

Fix bug when getting CFDI by UUID

---

.travis.yml
composer.json
phpstan.neon.dist
src/Captcha/Resolvers/DeCaptcherCaptchaResolver.php
src/Contracts/Filters.php
src/DownloadXML.php
src/Filters/BaseFilters.php
src/Filters/FiltersIssued.php
src/Filters/FiltersReceived.php
src/HtmlForm.php
src/Query.php
tests/Unit/MetadataListTest.php

The property $uuid was made to detect the central filter, it can be set from query and not using an internal property

Remove unused protected property BaseFilters::$uuid

---

src/Exceptions/LoginException.php
src/Exceptions/RuntimeException.php
src/Exceptions/SatHttpGatewayException.php
src/Exceptions/XmlDownloadError.php

Avoid conflicts as there is a RuntimeException class in the namespace \PhpCfdi\CfdiSatScraper\Exceptions

Rename \RuntimeException to SplRuntimeException

---

composer.json
docs/CHANGELOG.md
src/Exceptions/InvalidArgumentException.php
src/Filters/Options/ComplementsOption.php
tests/Unit/Filters/Options/ComplementsOptionTest.php

- El filtro por complemento `ComplementsOption` ya no es un `Enum`, ahora es un `MicroCatalog`. De esta forma se puede tener mucha más información relacionada con el complemento y por ejemplo poder ofrecer una lista de opciones de catálogos.
- La modificación de `ComplementsOption` es compatible con la versión anterior que implementaba enumeradores, con la diferencia de que si ahora se crea un complemento que no está en la lista no se retornará una excepción.

ComplementsOption extiende MicroCatalog en lugar de Enum

---

develop/install-development-tools
docs/CHANGELOG.md
tests/Integration/IntegrationTestCase.php

Este cambio no afecta la versión liberada y no requiere de un nuevo release.
- La construcción en Travis-CI se rompió porque PHPStan version 0.12.55 ya entiende las estructuras de control
de PHPUnit, por lo que sabe que el código subsecuente es código muerto. Se corrigieron las pruebas con problemas.
- Se actualizó la herramienta `develop/install-development-tools`

Corregir el build, roto por phpstan version 0.12.55

---

.github/workflows/build.yml
docs/CHANGELOG.md
tests/Unit/Captcha/Resolvers/AntiCaptchaTinyClient/AntiCaptchaTinyClientTest.php

Fix PHPStan issue: On `AntiCaptchaTinyClientTest` the prepared responses had malformed headers.
Improvement: Allow fail on Upload to Scrutinizer-CI step.

Build improvements

---

docs/CHANGELOG.md
src/Captcha/Resolvers/AntiCaptchaTinyClient/AntiCaptchaTinyClient.php

Se corrige un bug al consumir el servicio de Anti-Captcha donde estaba asumiendo que el código de error era un string vacío cuando en realidad es un número entero.

Error al usar Anti-Captcha

---

.github/workflows/build.yml
README.md
docs/CHANGELOG.md
docs/TODO.md
tests/Integration/Factory.php

Se agrega la documentación para configurar el cliente de cURL con `DEFAULT@SECLEVEL=1`.
Las pruebas se corren con `DEFAULT@SECLEVEL=1`.
Se agrega el código que ejemplifica cómo validar que la FIEL no es un CSD y que es válido al momento de la consulta.
Al ejecutar el flujo de integración continua, se usan los path en el archivo `phpcs.xml.dist`.

Documentación y correcciones pequeñas al CI

---

.phive/phars.xml
.php-cs-fixer.dist.php
README.md
docs/CHANGELOG.md
src/Filters/Options/ComplementsOption.php
src/Filters/Options/RfcOnBehalfOption.php
src/Filters/Options/RfcOption.php
src/Inputs/InputsByFilters.php
src/Internal/MetadataExtractor.php
src/Metadata.php
src/QueryByFilters.php
tests/Unit/Internal/MetadataExtractorTest.php
tests/Unit/MetadataTest.php
tests/Unit/QueryByFiltersTest.php
tests/_files/fake-to-extract-metadata-missing-uuid.html
tests/_files/fake-to-extract-metadata-one-cfdi.html
tests/_files/fake-to-extract-metadata-ten-cfdi.html
tests/_files/fake-to-extract-metadata-zero-cfdi.html
tests/_files/sample-response-receiver-using-filters-initial.html
tests/_files/sample-to-extract-metadata-one-cfdi.html

Se agrega el filtro `RfcOnBehalfOption`.
Se agrega la lectura de esta información en `Metadata` como `rfcACuentaTerceros`.
Se agrega la documentación para filtrar y leer el campo de *RFC a cuenta de terceros*.
Se documentan las propiedades en `Metadata` para acceder a ellas usando, por ejemplo `$metadata->uuid`.
Se agrega la documentación para configurar el cliente de cURL con `DEFAULT@SECLEVEL=1`.
Las pruebas se corren con `DEFAULT@SECLEVEL=1`.
Se agrega el código que ejemplifica cómo validar que la FIEL no es un CSD y que es válido al momento de la consulta.
Al ejecutar el flujo de integración continua, se usan los path en el archivo `phpcs.xml.dist`.

Version 3.1.0

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.phive/phars.xml
.php-cs-fixer.dist.php
README.md
composer.json
develop/ComoFunciona.md
develop/TestIntegracion.md
docs/CHANGELOG.md
docs/EjemploConsumo.md
docs/SEMVER.md
docs/TODO.md
docs/UPGRADE-2-3.md
phpunit.xml.dist
src/SatHttpGateway.php
src/Sessions/Ciec/CiecSessionManager.php
src/Sessions/Fiel/FielSessionManager.php
tests/Integration/Repository.php
tests/Unit/QueryByFiltersTest.php
tests/Unit/SatHttpGatewayTest.php
tests/generate-repository.php

Se admite la compatibilidad con Symfony 6. Esto evita que se tengan que degradar componentes a la versión 5.
Se depreca `SatHttpGatewayException::postLoginData` para crear el método específico
`SatHttpGatewayException::postCiecLoginData`. Esto no altera la funcionalidad actual.
Se agrega la dependencia faltante `mbstring`.
Se mejoran los test para probar valores idénticos en lugar de valores iguales.
Se actualizan las herramientas de desarrollo.
Se actualiza el archivo de configuración de `php-cs-fixer`.

Mantenimiento 2022-07-14 (versión 3.1.1)

---

.phive/phars.xml
.php-cs-fixer.dist.php
composer.json
docs/CHANGELOG.md
src/Filters/Options/ComplementsOption.php
src/Metadata.php
tests/Unit/MetadataListTest.php
tests/Unit/MetadataTest.php

- Se corrige `Metadata::hasResource` para que filtre correctamente cuando no existen recursos.
- Se corrige el flujo de integración continua.

Corrección de Metadata::hasResource y CI.

---

docs/CHANGELOG.md
src/Internal/MetadataExtractor.php
src/Metadata.php
tests/Unit/Internal/MetadataExtractorTest.php
tests/_files/fake-to-extract-metadata-missing-uuid.html
tests/_files/fake-to-extract-metadata-one-cfdi.html
tests/_files/fake-to-extract-metadata-ten-cfdi.html
tests/_files/fake-to-extract-metadata-zero-cfdi.html
tests/_files/sample-to-extract-metadata-one-cfdi.html

Se modifica la función `defaultFieldsCaptions()` ya que el SAT añadió dos columnas más (Motivo y Folio de Sustitución) para que posiblemente quede de la siguiente manera:
```php
public function defaultFieldsCaptions(): array
{
return [
'uuid' => 'Folio Fiscal',
'rfcEmisor' => 'RFC Emisor',
'nombreEmisor' => 'Nombre o Razón Social del Emisor',
'rfcReceptor' => 'RFC Receptor',
'nombreReceptor' => 'Nombre o Razón Social del Receptor',
'fechaEmision' => 'Fecha de Emisión',
'fechaCertificacion' => 'Fecha de Certificación',
'pacCertifico' => 'PAC que Certificó',
'total' => 'Total',
'efectoComprobante' => 'Efecto del Comprobante',
'estatusCancelacion' => 'Estatus de cancelación',
'estadoComprobante' => 'Estado del Comprobante',
'estatusProcesoCancelacion' => 'Estatus de Proceso de Cancelación', …
```

Actualización en el MetadataExtractor

---

.phive/phars.xml
docs/CHANGELOG.md
tests/Unit/SatScraperDownloadMethodsTest.php

- Se actualizaron las herramientas de desarrollo.
- Se aplicó la corrección de `php-cs-fixer`.
- Se corrigió el nombre de usuario de `@git-micotito` en este mismo archivo.

Corrección de construcción de integración continua

---

.github/workflows/build.yml
.phive/phars.xml
.php-cs-fixer.dist.php
docs/CHANGELOG.md
tests/Integration/HttpLogger.php
tests/Integration/Repository.php

- Se actualizaron las herramientas de desarrollo.
- Se corrige la firma (`phpdoc`) del método `HttpLogger::bodyToVars`.
- Se corrige el método `Repository::randomize` pues perdía las llaves del arreglo.
- Se corrige el archivo de configuración de `php-cs-fixer` porque la regla `no_trailing_comma_in_singleline_array` está deprecada.

Corrección del proceso de integración continua y mantenimiento

---

.github/workflows/build.yml
.github/workflows/coverage.yml
LICENSE
README.md
docs/CHANGELOG.md
src/Internal/MetadataExtractor.php
src/Metadata.php
tests/Unit/Internal/MetadataExtractorTest.php
tests/_files/fake-to-extract-metadata-missing-uuid.html
tests/_files/fake-to-extract-metadata-one-cfdi.html
tests/_files/fake-to-extract-metadata-ten-cfdi.html
tests/_files/fake-to-extract-metadata-zero-cfdi.html
tests/_files/sample-to-extract-metadata-one-cfdi.html

Se elimina la lectura de *Motivo de cancelación* (`motivoCancelacion`) y *Folio de sustitución* (`folioSustitucion`). Aparentemente, en la fecha 2023-01-04 el SAT ha eliminado estas columnas.
- Actualización de licencia a 2023. ¡Feliz año!.
- Actualización de flujos de trabajo sustituyendo la directiva `::set-output` con `$GITHUB_OUTPUT`.
- Corrección de la insignia del flujo de construcción `build`.

Quitar "Motivo de cancelación" y "Folio de sustitución" (Version 3.2.1)

---

.github/workflows/build.yml
.phive/phars.xml
LICENSE
docs/CHANGELOG.md
src/Internal/MetadataExtractor.php
src/Metadata.php
tests/Unit/Internal/MetadataExtractorTest.php
tests/Unit/MetadataTest.php
tests/_files/fake-to-extract-metadata-missing-uuid.html
tests/_files/fake-to-extract-metadata-one-cfdi.html
tests/_files/fake-to-extract-metadata-ten-cfdi.html
tests/_files/fake-to-extract-metadata-zero-cfdi.html
tests/_files/sample-to-extract-metadata-one-cfdi.html

Se agrega la lectura de *Motivo de cancelación* (`motivoCancelacion`) y *Folio de sustitución* (`folioSustitucion`). Aparentemente, en la fecha 2023-01-12 el SAT ha agregado estas columnas.
Previamente las había eliminado pero parece que se arrepintió.

Agregar "Motivo de cancelación" y "Folio de sustitución" (Version 3.2.2)

---

.phive/phars.xml
docs/CHANGELOG.md
tests/Unit/MetadataTest.php

- En las pruebas, se elimina una anotación para PHPStan para ignorar un error al realizar `unset` sobre una variable indefinida en un objeto de tipo `Metadata`.
- Actualización de herramientas de desarrollo.

Mantenimiento 2023-01-31

---

.phive/phars.xml
composer.json
docs/CHANGELOG.md
tests/Unit/SatHttpGatewayTest.php

Este PR corrige el workflow de construcción, no contiene cambios en el código por lo que no se necesita liberar una nueva versión.
- Actualización de herramientas de desarrollo.
- Se agrega la configuración en `composer.json` para no permitir el uso de *plugins* de `php-http/discovery`.
- En las pruebas, se refactoriza `SatHttpGatewayTest::testMethodPostLoginDataIsDeprecated` para probar que el método `postLoginData` está deprecado, dado que PHPUnit 9.6 descontinuó el método `expectDeprecation`.

Mantenimiento 20230213 (fix build)

---

.phive/phars.xml
composer.json
docs/CHANGELOG.md
src/Exceptions/ResourceDownloadError.php
src/ResourceDownloader.php
tests/Integration/Repository.php
tests/Integration/RepositoryItem.php
tests/Integration/RepositoryItemFactory.php
tests/Integration/RetrieveByUuidTest.php
tests/Unit/Exceptions/ResourceDownloadResponseErrorTest.php

Estos cambios se realizan en el entorno de desarrollo y pruebas, por lo que no es necesario hacer una liberación.
- Se refactoriza la clase `RepositoryItem` para que las responsabilidades de la creación de una instancia a partir de un arreglo se realizen en la clase `RepositoryItemFactory`.
- Se corrige el issue falso positivo encontrado por PHPStan al convertir un objeto a cadena de caracteres.
- Actualización de herramientas de desarrollo.

Mantenimiento 2023-05-25 (corrige integración continua)

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.phive/phars.xml
CONTRIBUTING.md
composer.json
develop/ComoFunciona.md
develop/EntornoDesarrollo.md
develop/TestIntegracion.md
docs/CHANGELOG.md
docs/EjemploConsumo.md
src/Sessions/Ciec/CiecLoginException.php
src/Sessions/Ciec/CiecSessionManager.php
tests/Unit/Sessions/Ciec/CiecLoginExceptionTest.php

Se corrige el mensaje relacionado con el envío de datos incorrectos al iniciar sesión usando CIEC.
Se corrige la dependencia de `CaptchaImage` por `CaptchaImageInterface` en `CiecLoginException`.
Se extrae la lógica para hacer la petición de acceso vía CIEC a un método separado.
En una prueba de concepto esto ayuda a crear la sesión usando un valor conocido de *Captcha*.
Se agregan los siguientes cambios en el entorno de desarrollo:
- Se corrige la liga del proyecto en el archivo `CONTRIBUTING.md`.
- Se actualizan las herramientas de desarrollo.
- Se agrega la herramienta `composer-normalize`.
- En el flujo de trabajo de cobertura de código se ejecuta usando PHP 8.2.
- Se elimina `PHP_CS_FIXER_IGNORE_ENV` del flujo de trabajo principal en el trabajo `php-cs-fixer`.
- Se agrega la opción …

Revisión 2023-06-22, correcciones menores (Versión 3.2.4)

---

.phive/phars.xml
docs/CHANGELOG.md
src/Internal/HtmlForm.php
src/Internal/MetadataExtractor.php

Fix catching crawler exception:
- class HtmlForm (internal) method filterCrawlerElements.
- class MetadataExtractor (internal) method obtainOnClickFromElement.
Thanks PHPStan!
Update development tools

Fix catching wrong exception (Version 3.2.5)

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.phive/phars.xml
composer.json
docs/CHANGELOG.md
tests/Integration/HttpLogger.php

- PHPStan encontró un problema en una especificación de tipo en un método de prueba, se ha corregido solo para que el proceso de integración continua no falle.
- Se actualizan las dependencias de los componentes de Symfony para soportar la versión 7.
- Se actualizan los flujos de trabajo de GitHub para usar las acciones versión 4.
- Se usa `php-version` en singular, en lugar de `php-versions`.
- Se actualizan las herramientas de desarrollo.

Mantenimiento 2024-05-22 (versión 3.3.1)

---

.github/workflows/build.yml
.phive/phars.xml
LICENSE
docs/CHANGELOG.md
src/Internal/MetaRefreshInspector.php
src/NullMetadataMessageHandler.php

- PHPStan encontró una comparación superflua que fue eliminada para corregir el proceso de integración continua.
- Se actualiza el año del archivo de licencia a 2024.
- Se actualizan las herramientas de desarrollo.

Mantenimiento 2024-09-09 (Versión 3.3.2)
